require('dotenv').config()
const express = require('express')
const app = express()
const cors = require('cors')
const connection = require('./db')
const userRoutes = require("./routes/users")
const authRoutes = require("./routes/auth")
const formRoutes = require("./routes/forms")
const editRoutes = require("./routes/movies")
//middleware
app.use(express.json())
app.use(cors())
const port = process.env.PORT || 8080
app.listen(port, () => console.log(`Nasłuchiwanie na porcie ${port}`))
connection()
app.use("/api/users", userRoutes)
app.use("/api/auth", authRoutes)
app.use("/api/forms", formRoutes)
app.use("/api/edit", editRoutes)

